### CREATE POST
POST http://localhost:8080/api/subSetting/CS Students/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "postName": "Thinking of getting a CS Degree",
  "description": "How long does it take?"
}

### LIKE POST
POST http://localhost:8080/api/subSetting/CS Students/post/6/vote
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "voteType": "UPVOTE"
}